Fixed status mismatch
kurago-dev/node-red-contrib-azure pull request #23
Opened 2023-07-13 13:55 UTC by unaipme

A "reconnection" is first attempted, so that we know for sure that the service is reachable, and that the green "Connected" status has a meaning at all.

2023-07-14 06:04 UTC, sakur33 approved these changes

2023-07-17 07:44 UTC, aitor-gamarra requested changes

2023-07-17 07:44 UTC, aitor-gamarra commented on azure-blob-storage.ts
> +  this.reconnect();
If there's no connection string configured on the node, Node-RED will crash

2023-07-17 09:04 UTC, aitor-gamarra approved these changes

2023-07-17 09:09 UTC, merged